ctul """
FlashForge Demo Script
Demonstrates the multi-agent pipeline without requiring API keys
"""

import asyncio
import zipfile
import io
import hashlib
import json
from pathlib import Path
from typing import Dict, Union

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Import only what's needed without heavy dependencies
from config import DESIGN_PRESETS, EVALUATION_CRITERIA


def demo_design_presets():
    """Demonstrate design presets"""
    print("\n" + "="*60)
    print("🎨 DESIGN PRESETS")
    print("="*60)
    
    for key, preset in DESIGN_PRESETS.items():
        print(f"\n📌 {preset['name']} ({key})")
        print(f"   {preset['description']}")
        colors = preset['tailwind_config']['colors']
        print(f"   Colors: Primary={colors['primary']}, Accent={colors['accent']}")


def demo_evaluation_criteria():
    """Demonstrate evaluation criteria"""
    print("\n" + "="*60)
    print("📊 EVALUATION CRITERIA")
    print("="*60)
    
    for category, data in EVALUATION_CRITERIA.items():
        print(f"\n📌 {category.upper()} (Weight: {data['weight']*100:.0f}%)")
        for sub, weight in data['subcriteria'].items():
            print(f"   • {sub}: {weight*100:.0f}%")


def create_demo_zip(files: Dict[str, str]) -> dict:
    """Simple ZIP creation for demo"""
    try:
        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
            for filename, content in files.items():
                zf.writestr(filename, content)
        
        zip_bytes = zip_buffer.getvalue()
        return {
            "success": True,
            "size_bytes": len(zip_bytes),
            "file_count": len(files),
            "checksum": hashlib.sha256(zip_bytes).hexdigest()
        }
    except Exception as e:
        return {"success": False, "error": str(e)}


def demo_packer():
    """Demonstrate packer functionality"""
    print("\n" + "="*60)
    print("📦 PACKER UTILITY")
    print("="*60)
    
    # Create sample web app
    files = {
        "index.html": """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FlashForge Demo</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100">
    <div class="container mx-auto p-8">
        <h1 class="text-4xl font-bold text-blue-600">Hello from FlashForge!</h1>
        <p class="mt-4 text-gray-700">Generated by AI Agent</p>
    </div>
</body>
</html>""",
        "README.md": "# Demo App\n\nGenerated by FlashForge"
    }
    
    result = create_demo_zip(files)
    
    if result["success"]:
        print(f"\n✅ ZIP created successfully!")
        print(f"   Files: {result['file_count']}")
        print(f"   Size: {result['size_bytes']} bytes")
        print(f"   Checksum: {result['checksum'][:16]}...")
    else:
        print(f"\n❌ Failed: {result['error']}")


def demo_settings():
    """Demonstrate settings"""
    print("\n" + "="*60)
    print("⚙️  CONFIGURATION")
    print("="*60)
    
    print(f"\n📌 App: FlashForge v1.0.0")
    print(f"   Primary LLM: groq (Mixtral)")
    print(f"   Fallback LLM: openai (GPT-4)")
    print(f"   Quality LLM: anthropic (Claude 3)")
    print(f"\n📌 Models:")
    print(f"   Groq: mixtral-8x7b-32768")
    print(f"   OpenAI: gpt-4-turbo-preview")
    print(f"   Anthropic: claude-3-opus-20240229")
    print(f"\n📌 Evaluation Weights:")
    print(f"   Functionality: 50%")
    print(f"   Design: 30%")
    print(f"   Speed: 20%")


def demo_agents_structure():
    """Demonstrate agent structure"""
    print("\n" + "="*60)
    print("🤖 AGENT PIPELINE")
    print("="*60)
    
    agents = [
        ("Planner", "Analyzes prompts and creates implementation plans"),
        ("Builder", "Generates HTML/CSS/JS with Tailwind CSS"),
        ("Critic", "Evaluates quality (50% func, 30% design, 20% speed)"),
        ("Fixer", "Automatically fixes identified issues")
    ]
    
    for i, (name, desc) in enumerate(agents, 1):
        print(f"\n{i}. 📌 {name} Agent")
        print(f"   {desc}")


async def main():
    """Run all demos"""
    print("\n" + "="*60)
    print("⚡ FlashForge DEMO")
    print("   Autonomous AI Agent for FlashForge Hackathon")
    print("="*60)
    
    demo_settings()
    demo_design_presets()
    demo_evaluation_criteria()
    demo_agents_structure()
    demo_packer()
    
    print("\n" + "="*60)
    print("✅ Demo Complete!")
    print("="*60)
    print("\nTo run the full agent:")
    print("  1. Set up API keys in .env file")
    print("  2. Run: python main.py --test")
    print("\n")


if __name__ == "__main__":
    asyncio.run(main())

